package com.programta.entity;
// Generated Dec 21, 2017 2:58:38 PM by Hibernate Tools 4.3.1



/**
 * Evaluasi generated by hbm2java
 */
public class Evaluasi  implements java.io.Serializable {


     private Integer idEvaluasi;
     private Intansi intansi;
     private Pekerja pekerja;
     private String kodeLhu;
     private String d1;
     private String d2;
     private String d3;
     private String kontrol;
     private String hp10;
     private String hp07;

    public Evaluasi() {
    }

    public Evaluasi(Intansi intansi, Pekerja pekerja, String kodeLhu, String d1, String d2, String d3, String kontrol, String hp10, String hp07) {
       this.intansi = intansi;
       this.pekerja = pekerja;
       this.kodeLhu = kodeLhu;
       this.d1 = d1;
       this.d2 = d2;
       this.d3 = d3;
       this.kontrol = kontrol;
       this.hp10 = hp10;
       this.hp07 = hp07;
    }
   
    public Integer getIdEvaluasi() {
        return this.idEvaluasi;
    }
    
    public void setIdEvaluasi(Integer idEvaluasi) {
        this.idEvaluasi = idEvaluasi;
    }
    public Intansi getIntansi() {
        return this.intansi;
    }
    
    public void setIntansi(Intansi intansi) {
        this.intansi = intansi;
    }
    public Pekerja getPekerja() {
        return this.pekerja;
    }
    
    public void setPekerja(Pekerja pekerja) {
        this.pekerja = pekerja;
    }
    public String getKodeLhu() {
        return this.kodeLhu;
    }
    
    public void setKodeLhu(String kodeLhu) {
        this.kodeLhu = kodeLhu;
    }
    public String getD1() {
        return this.d1;
    }
    
    public void setD1(String d1) {
        this.d1 = d1;
    }
    public String getD2() {
        return this.d2;
    }
    
    public void setD2(String d2) {
        this.d2 = d2;
    }
    public String getD3() {
        return this.d3;
    }
    
    public void setD3(String d3) {
        this.d3 = d3;
    }
    public String getKontrol() {
        return this.kontrol;
    }
    
    public void setKontrol(String kontrol) {
        this.kontrol = kontrol;
    }
    public String getHp10() {
        return this.hp10;
    }
    
    public void setHp10(String hp10) {
        this.hp10 = hp10;
    }
    public String getHp07() {
        return this.hp07;
    }
    
    public void setHp07(String hp07) {
        this.hp07 = hp07;
    }




}


