package com.programta.entity;
// Generated Dec 21, 2017 2:58:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pekerja generated by hbm2java
 */
public class Pekerja  implements java.io.Serializable {


     private Integer id;
     private Intansi intansi;
     private Rumus rumus;
     private int kdPekerja;
     private String divisi;
     private String namaPekerja;
     private String noKtp;
     private Set evaluasis = new HashSet(0);

    public Pekerja() {
    }

	
    public Pekerja(Intansi intansi, Rumus rumus, int kdPekerja, String divisi, String namaPekerja, String noKtp) {
        this.intansi = intansi;
        this.rumus = rumus;
        this.kdPekerja = kdPekerja;
        this.divisi = divisi;
        this.namaPekerja = namaPekerja;
        this.noKtp = noKtp;
    }
    public Pekerja(Intansi intansi, Rumus rumus, int kdPekerja, String divisi, String namaPekerja, String noKtp, Set evaluasis) {
       this.intansi = intansi;
       this.rumus = rumus;
       this.kdPekerja = kdPekerja;
       this.divisi = divisi;
       this.namaPekerja = namaPekerja;
       this.noKtp = noKtp;
       this.evaluasis = evaluasis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Intansi getIntansi() {
        return this.intansi;
    }
    
    public void setIntansi(Intansi intansi) {
        this.intansi = intansi;
    }
    public Rumus getRumus() {
        return this.rumus;
    }
    
    public void setRumus(Rumus rumus) {
        this.rumus = rumus;
    }
    public int getKdPekerja() {
        return this.kdPekerja;
    }
    
    public void setKdPekerja(int kdPekerja) {
        this.kdPekerja = kdPekerja;
    }
    public String getDivisi() {
        return this.divisi;
    }
    
    public void setDivisi(String divisi) {
        this.divisi = divisi;
    }
    public String getNamaPekerja() {
        return this.namaPekerja;
    }
    
    public void setNamaPekerja(String namaPekerja) {
        this.namaPekerja = namaPekerja;
    }
    public String getNoKtp() {
        return this.noKtp;
    }
    
    public void setNoKtp(String noKtp) {
        this.noKtp = noKtp;
    }
    public Set getEvaluasis() {
        return this.evaluasis;
    }
    
    public void setEvaluasis(Set evaluasis) {
        this.evaluasis = evaluasis;
    }




}


