package com.programta.entity;
// Generated Dec 21, 2017 2:58:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rumus generated by hbm2java
 */
public class Rumus  implements java.io.Serializable {


     private int kdRumus;
     private String namaRumus;
     private String r1;
     private String r2;
     private String tanda;
     private Set pekerjas = new HashSet(0);

    public Rumus() {
    }

	
    public Rumus(int kdRumus, String namaRumus, String r1, String r2, String tanda) {
        this.kdRumus = kdRumus;
        this.namaRumus = namaRumus;
        this.r1 = r1;
        this.r2 = r2;
        this.tanda = tanda;
    }
    public Rumus(int kdRumus, String namaRumus, String r1, String r2, String tanda, Set pekerjas) {
       this.kdRumus = kdRumus;
       this.namaRumus = namaRumus;
       this.r1 = r1;
       this.r2 = r2;
       this.tanda = tanda;
       this.pekerjas = pekerjas;
    }
   
    public int getKdRumus() {
        return this.kdRumus;
    }
    
    public void setKdRumus(int kdRumus) {
        this.kdRumus = kdRumus;
    }
    public String getNamaRumus() {
        return this.namaRumus;
    }
    
    public void setNamaRumus(String namaRumus) {
        this.namaRumus = namaRumus;
    }
    public String getR1() {
        return this.r1;
    }
    
    public void setR1(String r1) {
        this.r1 = r1;
    }
    public String getR2() {
        return this.r2;
    }
    
    public void setR2(String r2) {
        this.r2 = r2;
    }
    public String getTanda() {
        return this.tanda;
    }
    
    public void setTanda(String tanda) {
        this.tanda = tanda;
    }
    public Set getPekerjas() {
        return this.pekerjas;
    }
    
    public void setPekerjas(Set pekerjas) {
        this.pekerjas = pekerjas;
    }




}


